export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_RESISTER_REQUEST = "USER_RESISTER_REQUEST";
export const USER_RESISTER_SUCCESS = "USER_RESISTER_SUCCESS";
export const USER_RESISTER_FAIL = "USER_RESISTER_FAIL";

export const USER_PROFILE_DETAILS_REQUEST = "USER_PROFILE_DETAILS_REQUEST";
export const USER_PROFILE_DETAILS_SUCCESS = "USER_PROFILE_DETAILS_SUCCESS";
export const USER_PROFILE_DETAILS_FAIL = "USER_PROFILE_DETAILS_FAIL";

export const USER_PROFILE_UPDATE_REQUEST = "USER_PROFILE_UPDATE_REQUEST";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_FAIL = "USER_PROFILE_UPDATE_FAIL";
export const USER_PROFILE_UPDATE_RESET = "USER_PROFILE_UPDATE_RESET";
